version: '3.9'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: najwvhX1nB5J7ZpC

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: najwvhX1nB5J7ZpC
      ME_CONFIG_MONGODB_URL: mongodb://admin:najwvhX1nB5J7ZpC@mongo:27017/

  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://admin:najwvhX1nB5J7ZpC@mongo:27017/
      HTTP_PORT: 3000